### PR TITLE
Add Jump drive Remodel

### PR DESCRIPTION
**Pull request by Scrinarii1337**
Jump drive and broken jump drive Remodel

### CODE REVIEW

**Comment by MCOfficer** [comment]
ref endless-sky/endless-sky#6537

**Comment by quyykk** [comment]
As Zitchas mentioned in the other PR, the sprites have an extra unit of width and height which makes the dimensions odd numbers and thus blurry.

**Comment by Zitchas** [comment]
Just to clarify: For best results, the high-dpi versions of the images should be exactly double the regular versions. Which also means they will be even sizes.

**Review by Zitchas — APPROVED** [review]

**Review by Zitchas — APPROVED** [review]
... And now with sprites that are properly x2 the original ones. Looks good!

**Pull request merged**
