### PR TITLE
Keys panel shift table adjustment for autosteer feature

### PR DESCRIPTION
**Pull request by UnorderedSigh**
This updates the keys panel image to move the shift table up a bit, required by https://github.com/endless-sky/endless-sky/pull/8508

The assets for the keys panel are out of date, so I edited the png manually:

- https://github.com/endless-sky/endless-sky-assets/pull/128

### CODE REVIEW

**Comment by UnorderedSigh** [comment]
> You should remove the Pug images in this one.

Not sure how that got there. I'm going to close this PR and open a new one. It is better than corrupting the merge history.

**Comment by quyykk** [comment]
> Not sure how that got there. I'm going to close this PR and open a new one. It is better than corrupting the merge history.

you can always force push

**Comment by UnorderedSigh** [comment]
> you can always force push

Unfortunately, now that I closed and force-pushed, I cannot re-open it.

**Comment by quyykk** [comment]
github smh

**Comment by UnorderedSigh** [comment]
It's here now:

https://github.com/endless-sky/endless-sky-high-dpi/pull/354

**Pull request closed without merging**
