### PR TITLE
Corrected osprey

### PR DESCRIPTION
**Pull request by beccabunny**
endless-sky/endless-sky#4244

### CODE REVIEW

**Comment by Pointedstick** [comment]
In this PR, you've deleted the sprite rather than replacing it with the proposed new one.

**Comment by beccabunny** [comment]
Are you sure? It shows the new one on the "changes" page

**Comment by Amazinite** [comment]
Looks fine to me.

**Comment by Pointedstick** [comment]
Weird, ignore me...

**Pull request merged**
