### PR TITLE
copyright hotfix (high dpi)

### PR DESCRIPTION
**Pull request by ziproot**
I forgot to do an equivalent PR for the high dpi plugin for https://github.com/endless-sky/endless-sky/commit/bb3ec2f0ad6c7b47fc067fca01669b7d19a23d2c

### CODE REVIEW

**Comment by Saugia** [comment]
In #9731 you added the Unsplash License line at the bottom as well as updated several files' licenses to include that instead of the usual "taken from unsplash.com". Searching HighDPI shows that there are still various examples of this and the Unsplash license isn't included here.

**Comment by ziproot** [comment]
Oops, forgot about that.

**Comment by Saugia** [comment]
All set?

**Comment by ziproot** [comment]
Yes

**Pull request merged**
