### PR TITLE
feat(CI): Add workflow for building the Steam depot

### PR DESCRIPTION
**Pull request by tibetiroka**
Adds a workflow for building the Steam depot. This is currently triggered manually.

I will test that it creates the depot with the correct contents.

### CODE REVIEW

**Comment by tibetiroka** [comment]
Works. The generated steam depot can be checked in [this workflow](https://github.com/endless-sky/endless-sky-high-dpi/actions/runs/9372290456/job/25803435223).

**Comment by tibetiroka** [comment]
By the way, I could move this over to the release workflow in the main repo. Would that be more convenient?

**Comment by warp-core** [comment]
That'd be a question for @MCOfficer since he's the one that does that.
Since we don't run any workflows for a release over here, it certainly seems like it'd be more convenient to have it over there where we run that workflow anyway.
But, it might be odd/confusing for something related to this package to be in that repository. And, it's not really a big inconvenience to come over here and run a workflow.

**Comment by MCOfficer** [comment]
IMO the arguments for here or there kinda balance each other out, so let's pick the option with less complexity and have it be here.

**Pull request merged**
